<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anas" ignored="0" name="me" tests="2" failures="1" timestamp="28 Sep 2018 08:23:57 GMT" time="39.274" errors="0">
  <testcase name="testA" time="1.289" classname="script.TestDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at script.TestDemo.testA(TestDemo.java:18)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.003" classname="script.TestDemo2"/>
</testsuite> <!-- me -->
